SSID = "Write your twillio SSID here" #generated when you have created your twillio account"
AUTH_TOKEN = "write your twillio auth_token here"#you can access it from your twillio account dashboard
FROM_NUMBER = "This is the number generated by twillio"
TO_NUMBER = "This is your personal mobile number"#must add +91 in the beginning 
BOLT_API = "This your bolt api key"
DEVICE_ID = "This your bolt device id like BOLTXXXXXXXX"
